### PR TITLE
Num stores display

### PR DESCRIPTION
**Pull request by danny-george**
adds ability to set max num of stores displayed

### CODE REVIEW

**Comment by mukundc20-dev** [comment]
can you add ss

**Review by mariamabou — APPROVED** [review]
looks good to me but def include a SS and make sure anything you add follows the current design to remain consistent!

**Comment by danny-george** [comment]
image
image

**Review by mukundc20-dev — APPROVED** [review]
looks good to me!

**Comment by mariamabou** [comment]
great thanks for the ss

**Pull request merged**
