### PR TITLE
changing color scheme for results

### PR DESCRIPTION
**Pull request by StrawberryNougat**
I started changing the color scheme for the results tab, but I realized I started before pulling new UI changes, so I'll be doing those after I resolve the merge conflict and pull again

### CODE REVIEW

**Comment by NirjharDeb** [comment]
Gotcha! Can you add a screenshot as proof of success? Thanks!!

**Comment by StrawberryNougat** [comment]
colorschemechanges
Here is an example of what I did to the ratios/colors

**Review by NirjharDeb — APPROVED** [review]
Looks awesome to me! Great job!!

**Review by mukundc20-dev — APPROVED** [review]
looks great! love the color scheme

**Pull request merged**
