### PR TITLE
Added resetMap functionality

### PR DESCRIPTION
**Pull request by detoasty3**
Made it so that when you click on "Reset Map", the center reverts to Georgia Tech's location.

### CODE REVIEW

**Comment by NirjharDeb** [comment]
Looks good to me! Can you wait until PR 38 is merged (due to the complexity of the code there), then resolve merge conflicts in your PR and update? Also, please attach a screenshot to show that it works. Thanks!!

**Review by mariamabou — APPROVED** [review]
Looks good. Might look back on this a bit later.

**Comment by detoasty3** [comment]
Screenshot 2024-10-06 172514
Before clicking on "Reset Map"
Screenshot 2024-10-06 172534
After clicking on "Reset Map"

**Review by NirjharDeb — APPROVED** [review]
Thanks for the screenshot to demonstrate functionality. Approved!

**Pull request merged**
