### PR TITLE
Map markers

### PR DESCRIPTION
**Pull request by mukundc20-dev**
Added map markers to the map page, blue markers correspond to bookstores, red markers correspond to cafes.

### CODE REVIEW

**Review by StrawberryNougat — APPROVED** [review]
It looks fine to me, though I think some files were added that were already present? I don't think that should hurt anything, though

**Comment by NirjharDeb** [comment]
Can you attach the screenshot here for proof of success? Thanks

**Comment by mukundc20-dev** [comment]
markers_ss

**Comment by NirjharDeb** [comment]
Also, it seems like a lot of excess files were added. Can you go through these files, remove the unnecessary ones, and re-test locally? I would also highly recommend doing a 'mvn clean' after removing the unnecessary files.

**Pull request closed without merging**
