### PR TITLE
Zoom In Feature for Results

### PR DESCRIPTION
**Pull request by mariamabou**
Updated Zoom Feature

### CODE REVIEW

**Comment by mariamabou** [comment]
I added the ability to zoom in to the specific location that the user requested. This just makes the overall experience nicer, I understand that the user can click on the google maps link but this just streamlines the maps view for them, at least giving a quick understanding of the location of the building before rerouting to google maps! 
Screenshot 2024-10-06 at 11 45 31 AM

**Review by NirjharDeb — APPROVED** [review]
This looks good! Don't forget to resolve merge conflicts though...

**Comment by mariamabou** [comment]
great, will resolve ASAP!

**Comment by mariamabou** [comment]
Quick update: had to remove the springboot things and the google maps API key, all good now!

**Review by detoasty3 — APPROVED** [review]
Looks good!

**Pull request merged**
