### PR TITLE
marker clicking finished

### PR DESCRIPTION
**Pull request by mukundc20-dev**
When clicking on a marker, you can now see the place details in the sidebar

### CODE REVIEW

**Comment by mukundc20-dev** [comment]
ss2

**Comment by NirjharDeb** [comment]
Looks good to me. I recommend in a future PR adding unit tests for this for test coverage. Thanks!!

**Review by NirjharDeb — APPROVED** [review]

**Review by StrawberryNougat — APPROVED** [review]
This checks out, and it shouldn't cause any merge conflicts which is a relief lol

**Review by detoasty3 — APPROVED** [review]
Looks good to me too!

**Pull request merged**
