### PR TITLE
Panning of Map

### PR DESCRIPTION
**Pull request by mariamabou**
Updated the Effects on MapPages

### CODE REVIEW

**Comment by NirjharDeb** [comment]
I think I sort of understand what this PR is trying to achieve - enable the panning of maps. However, since I'm not really a front-end guy, it is a bit tough to say that this is correct based on just seeing the code.

Could you please update your PR with a screenshot to demonstrate that this works correctly? Thanks!!

**Comment by mariamabou** [comment]
Screenshot 2024-10-05 at 3 14 53 PM
the man should pan to a new location

**Review by NirjharDeb — APPROVED** [review]
After viewing the screenshot as proof of success, this looks good to me!

**Review by StrawberryNougat — APPROVED** [review]
Thanks for implementing this! The code itself is super readable too which I really appreciate

**Pull request merged**
