### PR TITLE
even more UI changes

### PR DESCRIPTION
**Pull request by mariamabou**
Finished what I started earlier which was just adding more to the UI design. Changed search bar, bookstore/cafe buttons and ai button

### CODE REVIEW

**Comment by mariamabou** [comment]
I meant to do this as part of the last PR but got interrupted but here's more UI changes. Changed Search button I was meaning to alter from the start, changed colors on bookstore/cafe button and centered + font changes, same with the ones on the results tab (changed width, inline, simple stuff etc etc).

**Review by detoasty3 — APPROVED** [review]
Looks good!

**Comment by mariamabou** [comment]
the ss aren't uploading properly : ( 
Screenshot 2024-10-07 at 5 36 00 PM
Screenshot 2024-10-07 at 5 35 46 PM

**Review by mukundc20-dev — APPROVED** [review]
lgtm

**Pull request merged**
