### PR TITLE
Settings button

### PR DESCRIPTION
**Pull request by detoasty3**

### CODE REVIEW

**Comment by NirjharDeb** [comment]
Can you add a screenshot to show how this works? Thanks!!

Also, you can add unit tests in a future PR.

**Comment by detoasty3** [comment]
Screenshot 2024-10-06 133734

**Review by NirjharDeb — APPROVED** [review]
Thanks for the screenshot - it looks great! Approved.

**Review by mariamabou — APPROVED** [review]
sounds good to me

**Pull request merged**
