### PR TITLE
Settings button

### PR DESCRIPTION
**Pull request by detoasty3**
Added the dropdown to the button; the buttons themselves still don't have functionality.

### CODE REVIEW

**Comment by NirjharDeb** [comment]
Can you add a description, fix merge conflicts, and a screenshot if appropriate? Thanks!!

**Review by mariamabou — APPROVED** [review]
looking through changed files and it seems like you're altering the dropdown menu, the changes look good on my end but could you include a brief description of what changed just so it is easier to follow along. Thanks!

**Comment by detoasty3** [comment]
Screenshot 2024-10-06 150847
The dropdown looks like this, and the buttons exist but currently have no functionality yet.

**Review by NirjharDeb — APPROVED** [review]
Looks good to me!

**Pull request merged**
