### PR TITLE
Map Markers (but without excess files)

### PR DESCRIPTION
**Pull request by mukundc20-dev**
same as earlier push but without the random excess files

### CODE REVIEW

**Comment by NirjharDeb** [comment]
Can you just attach the SS here for documentation purposes? Thanks!

**Comment by mukundc20-dev** [comment]
markers_ss

**Review by NirjharDeb — APPROVED** [review]
Looks good to me!

**Review by StrawberryNougat — APPROVED** [review]
Perfect! I think we're almost done now that this feature is in

**Pull request merged**
